---
- name: Configure password
  block:

    - name: Check /etc/xray/password
      ansible.builtin.stat:
        path: /etc/xray/password
      register: xray_password_stat

    - name: Generate password
      ansible.builtin.command:
        cmd: "openssl rand -base64 16"
      register: xray_generate_password
      changed_when: false
      when: not xray_password_stat.stat.exists

    - name: Write password to /etc/xray/password
      ansible.builtin.copy:
        content: "{{ xray_generate_password.stdout }}"
        dest: /etc/xray/password
        mode: "0600"
        owner: root
        group: root
      when: not xray_password_stat.stat.exists

    - name: Set fact xray_password fact (new password)
      ansible.builtin.set_fact:
        xray_password: "{{ xray_generate_password.stdout }}"
      when: not xray_password_stat.stat.exists

    - name: Read /etx/xray/password
      ansible.builtin.slurp:
        src: /etc/xray/password
      register: xray_read_password
      when: xray_password_stat.stat.exists

    - name: Set fact xray_password fact  (password from file)
      ansible.builtin.set_fact:
        xray_password: "{{ xray_read_password['content'] | b64decode }}"
      when: xray_password_stat.stat.exists
