---
- name: Configure xray
  become: true
  become_user: root
  become_method: ansible.builtin.sudo
  block:

    - name: Create /etc/xray
      ansible.builtin.file:
        path: /etc/xray
        state: directory
        mode: "0755"
        owner: root
        group: root

    - name: Create logfile
      ansible.builtin.file:
        path: "{{ xray_logfile }}"
        state: touch
        access_time: preserve
        modification_time: preserve
        mode: "0644"
        owner: root
        group: root

    - name: Set xray_image fact (used official image)
      ansible.builtin.set_fact:
        xray_image: "{{ xray_official_image }}:{{ xray_version }}"

    - name: Build handmade docker image
      ansible.builtin.include_tasks: build_handmade_image.yml
      when: use_xray_handmade_image

    - name: Configure uuid
      ansible.builtin.include_tasks: configure_uuid.yml

    - name: Configure keys
      ansible.builtin.include_tasks: configure_keys.yml

    - name: Configure short id
      ansible.builtin.include_tasks: configure_short_id.yml

    - name: Configure password
      ansible.builtin.include_tasks: configure_password.yml

    - name: Create config
      ansible.builtin.template:
        src: config.json.j2
        dest: /etc/xray/config.json
        mode: '0600'
        owner: root
        group: root
      register: config_file
      notify: Create QR code

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers

    - name: Run docker image {{ xray_image }}
      community.docker.docker_container:
        name: xray
        image: "{{ xray_image }}"
        command: run --config /etc/xray/config.json --format json
        restart_policy: always
        recreate: false
        ports:
          - "0.0.0.0:443:443"
        log_driver: syslog
        log_options:
          tag: xray
        volumes:
          - /etc/xray/config.json:/etc/xray/config.json
        env:
          _CONFIG_CHECKSUM: "{{ config_file.checksum | default('') }}"
        comparisons:
          '*': strict
